#!/bin/sh /etc/rc.common

START=50

CFILE=/tmp/cloudflare

start_service() {
    /usr/bin/cloudflare.sh &
}

shutdown() {
    rm $CFILE
}

stop_service() {
   shutdown
}

start() {
    start_service
}
stop() {
    stop_service
}
